# Author: msq
"""add p0 evidence chain tables

Revision ID: 01195e08d027
Revises: 3f52046a1239
Create Date: 2026-02-05 22:01:46.576440

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "01195e08d027"
down_revision: Union[str, None] = "3f52046a1239"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
