# Author: msq
"""add tool_traces

Revision ID: a2e59547cc18
Revises: 01195e08d027
Create Date: 2026-02-05 23:14:05.007375

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a2e59547cc18"
down_revision: Union[str, None] = "01195e08d027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
